### ISSUE TITLE
Import - Selected file fails field verification

### ISSUE THREAD

**Issue by srmatthe** [opengento/magento2-category-import-export#2] opened 2024-07-08 11:01 UTC
After selecting a file to import and then clicking the Upload and Import button the form fails with a validation error on the Select File to Import field.

![image](https://github.com/opengento/magento2-category-import-export/assets/22107041/e1667aa9-ca43-4516-8b18-53967a2fc682)

Removing the validation declaration for the field in view/adminhtml/ui_component/import_category_form.xml allows the file to be uploaded and processed correctly.

Nice plugin by the way.

**Comment by thomas-kl1** [comment] 2024-07-08 11:43
Wow didn't expected to have a user so quickly 😄 (it has been published last night!)

What Magento version do you use? I can't reproduce

**Comment by srmatthe** [comment] 2024-07-08 11:50
Haha, I did spot the age and didn't want to seem like complaining.

This is on 2.4.5-p8.  Pretty vanilla installation of Magento built for some theme development work.
Browser being used was Chrome.

I'll struggle for time to test further today but can have a go later in the week if needed.

**Comment by thomas-kl1** [comment] 2024-07-08 12:30
NVM I'm reproducing it now 🥴
Weird because it was working fine yesterday, I guess "cache" it is

**Comment by thomas-kl1** [comment] 2024-07-08 12:32
I'm going to release the fix and some improvement over the attributes selection on export tonight

**Comment by thomas-kl1** [comment] 2024-07-08 18:39
Beside that I've opened an issue on Magento repo, who know, maybe it will be fixed in a future!

**Comment by srmatthe** [comment] 2024-07-08 18:42
Cool.  Is the validation check meant to work on a file upload field like that then or is there a specific type for those?

**Comment by thomas-kl1** [comment] 2024-07-08 19:02
My guess is it is a native bug. Actually you setup on this field "file" an upload URL, so you can download a file with ajax and then it store the path. Maybe it is how it is intended to work "normally". In my opinion it should work anyhow we configured our field, to upload on submit or ajax.

**Closed as completed** 2024-07-08 20:06 UTC

**Comment by thomas-kl1** [comment] 2024-07-08 22:02
👋 @srmatthe the module is way more stable with the 0.3.0 release. You can now excluded available attributes from the config (catalog > catalog > category import export).
Also any invisible attributes could not be exported or imported.

**Comment by srmatthe** [comment] 2024-07-08 22:04
Excellent, thanks.  I'll have a play over the next couple of days.

**Comment by thomas-kl1** [comment] 2024-07-11 13:47
FYI @srmatthe the issue has been confirmed by Adobe. Magento eng team should work on it (no ETA).

**Comment by srmatthe** [comment] 2024-07-11 15:33
Hehe cool.  My first ever genuine and acknowledged bug :)
